# makefile generated by dtool
ifeq ($(strip $(APPNAME)),s0)
	proj_dir=$(solpro)/ads0
endif
 
ifeq ($(strip $(proj_dir)),)
$(error error : invalid app project: "$(APPNAME)".\
Run -s,-m first to renew "projects.conf" and total "$(solconf)/Makefile" )
endif

ifeq ($(strip $(TARGET)),)
MSGB=build
else
MSGB=$(strip $(TARGET))
endif

include /d/dt/mak/projs.mk
